DROP TABLE IF EXISTS Cars;
DROP TABLE IF EXISTS People;
DROP SCHEMA IF EXISTS tz CASCADE;
CREATE SCHEMA IF NOT EXISTS tz;
CREATE TABLE IF NOT EXISTS tz.cars (
    Reg_num VARCHAR(255) PRIMARY KEY,
    Mark VARCHAR(255) NOT NULL,
    Model VARCHAR(255) NOT NULL,
    Year INT,
    Owner_ID INT,
    CONSTRAINT fk_owner
        FOREIGN KEY(Owner_ID) 
        REFERENCES tz.peoples(ID)
        ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS tz.peoples (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Surname VARCHAR(255) NOT NULL,
    Patronymic VARCHAR(255)
);
